[context.production]
  [context.production.environment]
    BASE_HOSTNAME = "https://seldo.com"

[context.branch-deploy]
  [context.branch-deploy.environment]
    BASE_HOSTNAME = "https://staging--seldo.netlify.com"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/start-oauth"
  status = 302

[[redirects]]
  from = "/pictures/*"
  to = "https://seldo-dot-com-media.s3-us-west-1.amazonaws.com/pictures/:splat"
  status = 301

[[redirects]]
  from = "/downloads/*"
  to = "https://seldo-dot-com-media.s3-us-west-1.amazonaws.com/downloads/:splat"
  status = 301

[[redirects]]
  from = "/weblog/calendar"
  to = "/archive"
  status = 301

[[redirects]]
  from = "/weblog/:year/:month/:day/:slug"
  to = "/posts/:slug"
  status = 301

[[redirects]]
  from = "/weblog/:year/:month/:day"
  to = "/archive"
  status = 301

[[redirects]]
  from = "/weblog/:year/:month"
  to = "/archive"
  status = 301

[[redirects]]
  from = "/weblog/:year"
  to = "/archive"
  status = 301

[[redirects]]
  from = "/api/getposts"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/api/getposts/*"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/api/getall/*"
  to = "/rss.xml"
  status = 301

[[headers]]
  for = "/static/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
